include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: false
    prefer_single_quotes: true